version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m telegram.bot
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - api
    restart: unless-stopped 