version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: python run_local.py
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  telegram-bot:
    build: .
    env_file:
      - .env
    command: python run_telegram_bot.py
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs 